name: Metrics
on:
  # Schedule updates every 3 days to reduce frequency
  schedule: [{cron: "0 0 */3 * *"}]
  workflow_dispatch:
  # Only run on manual trigger or schedule, not on every push

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asakushen
          config_timezone: Asia/Shanghai
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Basic plugins that are stable
          plugin_introduction: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          
          plugin_calendar: yes
          plugin_calendar_limit: 3
          
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic
          
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
